### ISSUE TITLE
Transaction execution error

### ISSUE THREAD

**Issue by vzhilov** [EOSIO/eos-token-sale#21]
Can't pay ETH from my test KETH, getting the following error:

```
Transaction execution error.

Error: Transaction execution error.
    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7861:27885)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7862:26989
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7838:5
Transaction execution error.

Error: Transaction execution error.
    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7861:27885)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7862:26989
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7838:5
Error: MetaMask Tx Signature: User denied transaction signature. at TransactionController. (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:4350:25) at TransactionController.g (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:42698:16) at TransactionController.EventEmitter.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:42614:17) at TransactionController._setTxStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1555:14) at TransactionController.setTxStatusRejected (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1444:12) at TransactionController.cancelTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1313:12) at Proto.apply (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:33833:13) at Proto.handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:33809:19) at dnode.handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:34088:21) at dnode.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:34076:22)

Error: Error: MetaMask Tx Signature: User denied transaction signature.
    at TransactionController. (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:4350:25)
    at TransactionController.g (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:42698:16)
    at TransactionController.EventEmitter.emit (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:42614:17)
    at TransactionController._setTxStatus (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1555:14)
    at TransactionController.setTxStatusRejected (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1444:12)
    at TransactionController.cancelTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:1313:12)
    at Proto.apply (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:33833:13)
    at Proto.handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:33809:19)
    at dnode.handle (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:34088:21)
    at dnode.write (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/background.js:34076:22)
    at Object.InvalidResponse (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7861:27885)
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7862:26989
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:168:7
    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/scripts/inpage.js:7838:5
```

**Comment by vzhilov** [comment]
Ok, refreshed the page and tried two hours later and was fine.
