### ISSUE TITLE
EOS Token Sale Load error

### ISSUE THREAD

**Issue by jcalfee** [EOSIO/eos-token-sale#7]
This is what I did:

* opened: https://eosio.github.io/eos-token-sale/
* unlock my Metamask wallet (main network)
* reload the browser
* the error below shows up in the browser's main window
* The console shows that I do have an account: `window.web3.eth.accounts.length >= 1`

```
EOS Token Sale

Loading...

new BigNumber() not a base 16 number:

BigNumber Error: new BigNumber() not a base 16 number: 
    at T (chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6728:28898)
    at chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6729:2445
    at new e (chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6728:26415)
    at i._ [as _outputFormatter] (chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6725:9861)
    at chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6725:14661
    at i.decode (chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6725:14683)
    at chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6725:7489
    at Array.map (native)
    at d.decodeParams (chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6725:7462)
    at s.unpackOutput (chrome-extension://edfjhoecmhbokdkooahplghgdogagnem/scripts/inpage.js:6726:5426)
```

I started with the code, it is able to load the contracts here:
```javascript
    eos_sale  = web3.eth.contract(eos_sale_abi).at(eos_sale_address_kovan)
    eos_token = web3.eth.contract(eos_token_abi).at(eos_token_address_kovan)
```

The following async code is a bit hard to debug though.  I think something is getting passed back to through web3 to cause this error.

This happens when Metamask is pointed to the main network.  Also happens when pointed to the 1st test network..

**Comment by landrew** [comment]
Getting the same error.

**Comment by dbrock** [comment]
Ah, yeah, you need to use the Kovan network.

I'll put in a better error message.
